project:
  type: website
  output-dir: docs

page-navigation: true
  
website:
  title: "HLG-MOS Project on SOSS"
  site-path: /OSS/
  navbar:
    logo: "assets/img/oss_charter_logo.png"
    left:
      - href: index.qmd
        text: Home
      - href: principles.qmd
        text: "The Principles"
      - case_studies.qmd
      - href: major_topics.qmd
        text: "Major Topics"
      - background.qmd
      - resources.qmd
    tools:
      - icon: file-pdf
        menu: 
          - text: Project Report
            href: https://unece.org/sites/default/files/2025-02/Statistical%20Open%20Source%20Software%20-%20Charter%20and%20Report.pdf     
          - text: CES Endorsement
            href: https://unece.org/sites/default/files/2025-06/Decisions%20-%20day%203.pdf
      - icon: linkedin
        href: https://www.linkedin.com/showcase/unece-modernisation-of-official-statistics/
      - icon: github
        menu: 
          - text: Source Code
            href: https://github.com/UNECE/OSS
          - text: Submit an Issue/Request
            href: https://github.com/unece/oss/issues

  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: This work is licensed under [CC BY 4.0](http://creativecommons.org/licenses/by/4.0/) 
    center: |
      [![ModernStats Logo](/assets/img/modernstats_footer.png){fig-alt="ModernStats" width=110px}](https://unece.org/statistics/modernstats)
  favicon: /assets/img/oss_charter_logo.png
  back-to-top-navigation: true

format:
  html:
    theme: cerulean
    css: /assets/styling/styles.css
    toc: true
    toc-location: left


editor: source
