project:
  type: website
  output-dir: docs
  
website:
  title: "HLG-MOS OSS Charter"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - charter.qmd
      - case_studies.qmd
      - major_topics.qmd
      - acknowledgements.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/showcase/unece-modernisation-of-official-statistics/
      - icon: github
        href: https://github.com/UNECE/OSS_Charter
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, UNECE"

format:
  html:
    theme: cerulean
    mainfont: Roboto
    toc: true

editor: source

