project:
  type: website
  output-dir: docs
  
website:
  title: "HLG-MOS OSSP"
  navbar:
    logo: "img/UN Emblem_White.png"
    left:
      - href: index.qmd
        text: Home
      - charter.qmd
      - case_studies.qmd
      - major_topics.qmd
      - acknowledgements.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/showcase/unece-modernisation-of-official-statistics/
      - icon: github
        href: https://github.com/UNECE/OSS_Charter
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: © Copyright 2024, UNECE 
      [![UNECE Logo](/img/favicon_unece.png){fig-alt="UNECE" width=20px}](https://unece.org)
    center: |
      [![ModernStats Logo](/img/modernstats_footer.png){fig-alt="ModernStats" width=110px}](https://unece.org/statistics/modernstats)
  favicon: /img/favicon_unece.png

format:
  html:
    theme: cerulean
    mainfont: Roboto
    toc: true

editor: source

