project:
  type: website
  output-dir: docs
  
website:
  title: "HLG-MOS Open-Source Software Charter"
  navbar:
    logo: "img/UN Emblem_White.png"
    left:
      - href: index.qmd
        text: Home
      - href: charter.qmd
        text: "The Principles"
      - case_studies.qmd
      - major_topics.qmd
      - background.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/showcase/unece-modernisation-of-official-statistics/
      - icon: github
        href: https://github.com/UNECE/OSS_Charter
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: This work is licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/) 
    center: |
      [![ModernStats Logo](/img/modernstats_footer.png){fig-alt="ModernStats" width=110px}](https://unece.org/statistics/modernstats)
  favicon: /img/favicon_unece.png

format:
  html:
    theme: cerulean
    mainfont: Roboto, Arial, sans-serif
    toc: true

editor: source

