---
title: "Resources"
sidebar: false
---

# Getting Started With Open-Source

## Links

-   [Work of the UNECE High-Level Group for the Modernisation of Official Statistics](https://unece.org/statistics/networks-of-experts/high-level-group-modernisation-statistical-production-and-services)

-   [Outputs of the UNEC Statistical Modernisation Unit](https://unece.org/statistics/modernstats)

-   [The Awesome List of Official Statistics](https://github.com/SNStatComp/awesome-official-statistics-software)

-   The ModernStats Carpentries (*note: the lessons are under construction*)

    -   [Python](https://unece.github.io/ModernStats_Python/) / [Git](https://unece.github.io/ModernStats_Git/) / [R](https://unece.github.io/ModernStats_Python/R)

-   [ESS Principles on Open-Source Software](https://os4os.pages.code.europa.eu/pbbp/principles.html)

-   [SDMX OS Resources](https://www.sdmx.io/)

## Papers

...

# Contacts

The following members of the working group that prepared the contents of this site are available to contact for clarification requests and support in introducing open-source software into NSOs.

|        Name         |     Organisation        | Contact Info                   |  
|---------------------|-------------------------|--------------------------------|
| Carlo Vaccari       | Independent Contractor  | vaccaricarlo at gmail dot com  |  
| Olav ten Bosch      | CBS                     | o.tenbosch at  cbs dot nl      |
| Jonathan Challener  | OECD                    | contact at siscc dot org       | 
| Marcello D'Orazio   | Istat                   | madorazi at istat dot it       | 

: Member Details {.striped .hover}



::: callout-note
Web site under construction
:::
